# Generated by Django 5.2.4 on 2025-07-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wikibase', '0002_populate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('wikibase.item',),
        ),
    ]
