# Generated by Django 5.2.4 on 2025-10-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pecunia', '0003_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecunia.item')),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pecunia.property')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='ItemPropertyAdminProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Property order list',
                'verbose_name_plural': 'Property order lists',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pecunia.item',),
        ),
        migrations.AlterUniqueTogether(
            name='itemproperty',
            unique_together={('item', 'prop')},
        ),
    ]
