# Generated by Django 5.2.4 on 2025-10-25 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pecunia', '0004_itemproperty'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemProperty',
            new_name='PropertyOrderPreference',
        ),
    ]
