# Generated by Django 5.2.4 on 2025-07-25 07:58

import django.db.models.deletion
import wikibase.models.base
import wikibase.models.datatypes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.value')),
            ],
            bases=('wikibase.value',),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.value')),
            ],
            bases=('wikibase.value',),
        ),
        migrations.CreateModel(
            name='PropertySnak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'value'), (1, 'somevalue'), (2, 'novalue')])),
                ('value', wikibase.models.base.InheritanceForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='using_as_value_snaks', to='wikibase.value')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceSnak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaks', to='wikibase.referencerecord')),
                ('snak', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='wikibase.propertysnak')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(-1, 'deprecated'), (0, 'normal'), (1, 'preferred')])),
                ('mainsnak', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='used_in_statement', to='wikibase.propertysnak')),
                ('subject', wikibase.models.base.InheritanceForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='wikibase.entity')),
            ],
        ),
        migrations.AddField(
            model_name='referencerecord',
            name='statement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_records', to='wikibase.statement'),
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikibase.propertysnak')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifiers', to='wikibase.statement')),
            ],
        ),
        migrations.CreateModel(
            name='MonolingualTextValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('language', models.CharField(max_length=3)),
                ('text', models.TextField()),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('value', models.TextField()),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='UrlValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('value', models.TextField()),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='Datatype',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.entity')),
                ('class_name', models.CharField(max_length=50)),
            ],
            bases=('wikibase.entity',),
        ),
        migrations.CreateModel(
            name='DescribedEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.entity')),
            ],
            bases=('wikibase.entity',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('describedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.describedentity')),
                ('display_id', models.IntegerField(default=1, unique=True)),
            ],
            bases=('wikibase.describedentity',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('describedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.describedentity')),
                ('display_id', models.IntegerField(default=1, unique=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='wikibase.datatype')),
            ],
            bases=('wikibase.describedentity',),
        ),
        migrations.CreateModel(
            name='Alias',
            fields=[
                ('monolingualtextvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.monolingualtextvalue')),
                ('described_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='wikibase.describedentity')),
            ],
            bases=('wikibase.monolingualtextvalue',),
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('monolingualtextvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.monolingualtextvalue')),
                ('described_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='wikibase.describedentity')),
            ],
            bases=('wikibase.monolingualtextvalue',),
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('monolingualtextvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.monolingualtextvalue')),
                ('described_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='wikibase.describedentity')),
            ],
            bases=('wikibase.monolingualtextvalue',),
        ),
        migrations.CreateModel(
            name='TimeValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('time', models.CharField(max_length=40)),
                ('timezone', models.IntegerField()),
                ('precision', models.IntegerField(blank=True, choices=[(0, 'Billion years'), (1, '100 million years'), (2, '10 million years'), (3, 'Million years'), (4, '100 thousand years'), (5, '10 thousand years'), (6, 'Thousand years'), (7, 'Century'), (8, 'Decade'), (9, 'Year'), (10, 'Month'), (11, 'Day'), (12, 'Hour'), (13, 'Minute'), (14, 'Second')], null=True)),
                ('after', models.IntegerField(blank=True, null=True)),
                ('before', models.IntegerField(blank=True, null=True)),
                ('calendar_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.item')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='QuantityValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('number', models.FloatField()),
                ('lower', models.FloatField(blank=True, null=True)),
                ('upper', models.FloatField(blank=True, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wikibase.item')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='ItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wikibase.item')),
            ],
        ),
        migrations.CreateModel(
            name='GlobeCoordinatesValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('precision', models.DecimalField(decimal_places=9, max_digits=12, validators=[wikibase.models.datatypes.positive])),
                ('globe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.item')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.AddField(
            model_name='propertysnak',
            name='property',
            field=wikibase.models.base.InheritanceForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='using_as_property_snaks', to='wikibase.property'),
        ),
        migrations.CreateModel(
            name='PropertyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wikibase.property')),
            ],
        ),
    ]
