# Generated by Django 5.1.3 on 2025-03-29 08:36

import django.core.validators
import django.db.models.deletion
import wikibase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Snak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DataValue',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.value')),
            ],
            bases=('wikibase.value',),
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('value_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.value')),
                ('identifier', wikibase.models.IriField()),
            ],
            bases=('wikibase.value',),
        ),
        migrations.CreateModel(
            name='PropertySnak',
            fields=[
                ('snak_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.snak')),
            ],
            bases=('wikibase.snak',),
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(choices=[(-1, 'Deprecated'), (0, 'Normal'), (1, 'Preferred')], validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)])),
                ('mainSnak', wikibase.models.InheritanceForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='wikibase.snak')),
                ('subject', wikibase.models.InheritanceForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wikibase.entity')),
            ],
        ),
        migrations.CreateModel(
            name='ReferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snak', wikibase.models.InheritanceForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.snak')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='wikibase.statement')),
            ],
        ),
        migrations.CreateModel(
            name='MultilingualMultiTextValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='MultilingualTextValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='QuantityValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('number', models.FloatField()),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('value', models.TextField()),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='TimeValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('time', models.CharField(max_length=40)),
                ('timezone', models.IntegerField()),
                ('precision', models.IntegerField(blank=True, choices=[(0, 'Billion years'), (1, '100 million years'), (2, '10 million years'), (3, 'Million years'), (4, '100 thousand years'), (5, '10 thousand years'), (6, 'Thousand years'), (7, 'Century'), (8, 'Decade'), (9, 'Year'), (10, 'Month'), (11, 'Day')], null=True)),
                ('after', models.IntegerField(blank=True, null=True)),
                ('before', models.IntegerField(blank=True, null=True)),
                ('calendar_model', wikibase.models.IriField()),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='Datatype',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.entity')),
                ('class_name', models.CharField(max_length=50)),
            ],
            bases=('wikibase.entity',),
        ),
        migrations.CreateModel(
            name='DescribedEntity',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.entity')),
                ('aliases', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliased_items', to='wikibase.multilingualmultitextvalue')),
                ('descriptions', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='described_items', to='wikibase.multilingualtextvalue')),
                ('labels', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labelled_items', to='wikibase.multilingualtextvalue')),
            ],
            bases=('wikibase.entity',),
        ),
        migrations.CreateModel(
            name='PropertyNoValueSnak',
            fields=[
                ('propertysnak_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.propertysnak')),
            ],
            bases=('wikibase.propertysnak',),
        ),
        migrations.CreateModel(
            name='PropertySomeValueSnak',
            fields=[
                ('propertysnak_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.propertysnak')),
            ],
            bases=('wikibase.propertysnak',),
        ),
        migrations.AddField(
            model_name='propertysnak',
            name='statement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikibase.statement'),
        ),
        migrations.CreateModel(
            name='MonolingualMultiTextValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('lang_code', models.CharField(max_length=3)),
                ('values', models.TextField()),
                ('multilingual_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikibase.multilingualmultitextvalue')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='MonolingualTextValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('lang_code', models.CharField(max_length=3)),
                ('value', models.TextField()),
                ('multilingual_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wikibase.multilingualtextvalue')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('describedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.describedentity')),
                ('display_id', models.IntegerField(default=1, unique=True)),
            ],
            bases=('wikibase.describedentity',),
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('describedentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.describedentity')),
                ('display_id', models.IntegerField(default=1, unique=True)),
                ('data_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='wikibase.datatype')),
            ],
            bases=('wikibase.describedentity',),
        ),
        migrations.CreateModel(
            name='PropertyValueSnak',
            fields=[
                ('propertysnak_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.propertysnak')),
                ('value', wikibase.models.InheritanceForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.value')),
            ],
            bases=('wikibase.propertysnak',),
        ),
        migrations.CreateModel(
            name='UnitQuantityValue',
            fields=[
                ('quantityvalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.quantityvalue')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.item')),
            ],
            bases=('wikibase.quantityvalue',),
        ),
        migrations.CreateModel(
            name='GlobeCoordinatesValue',
            fields=[
                ('datavalue_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('latitude', models.DecimalField(decimal_places=9, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=9, max_digits=12)),
                ('precision', models.DecimalField(decimal_places=9, max_digits=12, validators=[wikibase.models.positive])),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.item')),
            ],
            bases=('wikibase.datavalue',),
        ),
        migrations.AddField(
            model_name='propertysnak',
            name='property',
            field=wikibase.models.InheritanceForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wikibase.property'),
        ),
        migrations.CreateModel(
            name='PropertyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikibase.property')),
            ],
        ),
        migrations.CreateModel(
            name='ItemMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wikibase.item')),
            ],
        ),
        migrations.CreateModel(
            name='UrlValue',
            fields=[
                ('datavalue_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='wikibase.datavalue')),
                ('value', models.TextField()),
            ],
            bases=('wikibase.datavalue',),
        ),
    ]
